version: '3.7'

services:

    redisdb:
        image: redis:alpine
        # command: redis-server --requirepass password
        container_name: redisdb
        restart: always        
        ports:
            - "6379:6379"
        volumes:
            - ./storage/redis1/data:/data
        environment:
            - REDIS_REPLICATION_MODE=master
   
    sqldb:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
        - SA_PASSWORD=09128986248M@m
        - ACCEPT_EULA=Y
        ports:
        - "1432:1433"
        restart: always
        container_name: sqldb
        volumes:
            - ./storage/sqldb1/data:/data

    rabbitmq:
        container_name: rabbitmq
        environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
        ports:
        - "5672:5672"
        - "15672:15672"
        volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        restart: always
            
networks: 
     default: 
       external: true
       name: appliance 